@@include('libs/swiper.min.js', {})
@@include('libs/inputmask.min.js', {})
@@include('libs/datepicker-full.min.js', {})
@@include('libs/tippy.js', {})
@@include('libs/nouislider.js', {})
@@include('libs/wNumb.min.js', {})